anchor_version = "0.24.2"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

# [provider]
# cluster = "localnet"
# wallet = "./tests/test-key.json" # twLqUrEvBPdtWFusa4MSWqkyE7TyhJTv3xBXiLYUNcX

[provider]
cluster = "devnet"
wallet = "./local/keys/authority_6QSBsLf29rAghS4y1Sc7fbZRp8xhVEKipfD4msnnrzo2.json"

[programs.mainnet]
cardinal_token_manager = "39xubSermwXqcSPu2qEHSspGVmsVZYBnA8RbFqhMLbFK"
cardinal_paid_claim_approver = "Hv6ppuT2mvHjgpSQVuQnvT4hUTLjr1XgrqKyVbqzWRpu"
cardinal_time_invalidator = "AmoML37av2K7Cn4p5s2uYvdftC6v47RQveaAD1vPEGck"
cardinal_use_invalidator = "Ea82cLwGjJgFNwvNqKW3bBHBefWmN2n36C7roQMeiY7R"
cardinal_payment_manager = '3GT5Q6wwXwfDUcMAn6h4XCtmqSVFLp9eL7WQjKshNK3L'

[programs.devnet]
cardinal_token_manager = "39xubSermwXqcSPu2qEHSspGVmsVZYBnA8RbFqhMLbFK"
cardinal_paid_claim_approver = "Hv6ppuT2mvHjgpSQVuQnvT4hUTLjr1XgrqKyVbqzWRpu"
cardinal_time_invalidator = "AmoML37av2K7Cn4p5s2uYvdftC6v47RQveaAD1vPEGck"
cardinal_use_invalidator = "Ea82cLwGjJgFNwvNqKW3bBHBefWmN2n36C7roQMeiY7R"
cardinal_payment_manager = '3GT5Q6wwXwfDUcMAn6h4XCtmqSVFLp9eL7WQjKshNK3L'

[programs.testnet]
cardinal_token_manager = "39xubSermwXqcSPu2qEHSspGVmsVZYBnA8RbFqhMLbFK"
cardinal_paid_claim_approver = "Hv6ppuT2mvHjgpSQVuQnvT4hUTLjr1XgrqKyVbqzWRpu"
cardinal_time_invalidator = "AmoML37av2K7Cn4p5s2uYvdftC6v47RQveaAD1vPEGck"
cardinal_use_invalidator = "Ea82cLwGjJgFNwvNqKW3bBHBefWmN2n36C7roQMeiY7R"
cardinal_payment_manager = '3GT5Q6wwXwfDUcMAn6h4XCtmqSVFLp9eL7WQjKshNK3L'

[programs.localnet]
cardinal_token_manager = "39xubSermwXqcSPu2qEHSspGVmsVZYBnA8RbFqhMLbFK"
cardinal_paid_claim_approver = "Hv6ppuT2mvHjgpSQVuQnvT4hUTLjr1XgrqKyVbqzWRpu"
cardinal_time_invalidator = "AmoML37av2K7Cn4p5s2uYvdftC6v47RQveaAD1vPEGck"
cardinal_use_invalidator = "Ea82cLwGjJgFNwvNqKW3bBHBefWmN2n36C7roQMeiY7R"
cardinal_payment_manager = '3GT5Q6wwXwfDUcMAn6h4XCtmqSVFLp9eL7WQjKshNK3L'
