anchor_version = "0.24.2"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json" # twLqUrEvBPdtWFusa4MSWqkyE7TyhJTv3xBXiLYUNcX

[programs.mainnet]
cardinal_token_manager = "9WDgSgB9S54ui97UfY2shegJ764ScgwjDRLEhqLYS3e"
cardinal_paid_claim_approver = "9ekqCtEXJVRU5jdGxknES8Rs4nwF8g9ETagDtGUVAvTB"
cardinal_time_invalidator = "4SXNGLfQVMxrTJdJNArtfCM14grtzseH7ja8dMHCJpf8"
cardinal_use_invalidator = "CrqZJ1frYpEvmJDR4zKpJNicrPDNwKKUKevetmk7Eajo"
cardinal_payment_manager = '4nYmFoLLdYiHhceqWWaF2Hjmx2TUWg4FQQfYpWCMmg5n'

[programs.devnet]
cardinal_token_manager = "9WDgSgB9S54ui97UfY2shegJ764ScgwjDRLEhqLYS3e"
cardinal_paid_claim_approver = "9ekqCtEXJVRU5jdGxknES8Rs4nwF8g9ETagDtGUVAvTB"
cardinal_time_invalidator = "4SXNGLfQVMxrTJdJNArtfCM14grtzseH7ja8dMHCJpf8"
cardinal_use_invalidator = "CrqZJ1frYpEvmJDR4zKpJNicrPDNwKKUKevetmk7Eajo"
cardinal_payment_manager = '4nYmFoLLdYiHhceqWWaF2Hjmx2TUWg4FQQfYpWCMmg5n'

[programs.testnet]
cardinal_token_manager = "9WDgSgB9S54ui97UfY2shegJ764ScgwjDRLEhqLYS3e"
cardinal_paid_claim_approver = "9ekqCtEXJVRU5jdGxknES8Rs4nwF8g9ETagDtGUVAvTB"
cardinal_time_invalidator = "4SXNGLfQVMxrTJdJNArtfCM14grtzseH7ja8dMHCJpf8"
cardinal_use_invalidator = "CrqZJ1frYpEvmJDR4zKpJNicrPDNwKKUKevetmk7Eajo"
cardinal_payment_manager = '4nYmFoLLdYiHhceqWWaF2Hjmx2TUWg4FQQfYpWCMmg5n'

[programs.localnet]
cardinal_token_manager = "9WDgSgB9S54ui97UfY2shegJ764ScgwjDRLEhqLYS3e"
cardinal_paid_claim_approver = "9ekqCtEXJVRU5jdGxknES8Rs4nwF8g9ETagDtGUVAvTB"
cardinal_time_invalidator = "4SXNGLfQVMxrTJdJNArtfCM14grtzseH7ja8dMHCJpf8"
cardinal_use_invalidator = "CrqZJ1frYpEvmJDR4zKpJNicrPDNwKKUKevetmk7Eajo"
cardinal_payment_manager = '4nYmFoLLdYiHhceqWWaF2Hjmx2TUWg4FQQfYpWCMmg5n'
